### ISSUE TITLE
Include a README with instructions for running?

### ISSUE THREAD

**Issue by jrmuizel** [devos50/qemu-ios#1]
This would be helpful for others wanting to try it out and hoping to contribute

**Comment by xet7** [comment]
Maybe some info here? Just found this, I did not read all related info:

- Branch: https://github.com/devos50/qemu/tree/ipod_touch_1g
- https://devos50.github.io/blog/2022/ipod-touch-qemu/
- https://news.ycombinator.com/item?id=34095830

**Comment by devos50** [comment]
This issue should be addressed sufficiently (for the IT2G): https://github.com/devos50/qemu-ios/blob/ipod_touch_2g/RUNNING.md
