### ISSUE TITLE
QEMU keeps repeating same string of characters

### ISSUE THREAD

**Issue by Marko2155** [devos50/qemu-ios#177]
When i run the command `./arm-softmmu/qemu-system-arm -M iPod-Touch,bootrom=/Users/marko2155/Downloads/bootrom,nand=/Users/marko2155/Downloads/nand,nor=/Users/marko2155/Downloads/nor.bin -serial mon:stdio -cpu max -m 2G -d unimp`, it does a lot of stuff but then ends up repeating this: 
<img width="1118" alt="Screenshot 2024-08-07 at 8 53 28 PM" src="https://github.com/user-attachments/assets/f5cb7fad-d706-4246-af6a-74b3f7f87447">

**Comment by daniilfigasystems** [comment]
this is kernel feature, you cannot disable it.

**Comment by Marko2155** [comment]
well now its kernel panicking

**Comment by daniilfigasystems** [comment]
Can you send output log?

**Comment by Marko2155** [comment]
can't, i deleted everything after posting this, i'm off to do other stuff though soo...... [CLOSED]
