### ISSUE TITLE
Use new building method (Meson/Ninja)

### ISSUE THREAD

**Issue by XVilka** [devos50/qemu-ios#5]
Mainstream QEMU long time switched to Meson. Thus, it would make sense to update the article to use the corresponding building procedure. Moreover, it would be nice to rebase on top of the latest QEMU 7.2.0 release to include many fixes that happened since 2021, ability to run on MacOS M1 among them.

https://wiki.qemu.org/ChangeLog/7.2

**Comment by devos50** [comment]
Thanks for you suggestion! I'll have a look at it when I have more time.

**Comment by devos50** [comment]
I just rebased the `ipod_touch_2g` branch on top of QEMU 8.2.0 so I consider this issue fixed 👍
